### PR TITLE
Tl classifier

### PR DESCRIPTION
**Pull request by georgios-v**
DO NOT MERGE!

I have stripped down the original [classifier](https://github.com/georgios-v/CarND-Capstone/tree/classifier) branch to its bare minimum files.

Please review that everything is correct and complete. If it is, remove the [classifier](https://github.com/georgios-v/CarND-Capstone/tree/classifier) branch (remove as in delete completely).

We must be able to fit our repository onto a project workspace. The available space is only 2.8G. The current size of the repo reached 4G.

Once the size is smaller please:
- open a workspace
- open a terminal
- clone the repo
- navigate to 'CarND-Capstone/classifier/build'
- execute:
 `
export PYTHONPATH=$(pwd)"/../src/"; python test.py ../my_traffic_inference_graph_20000_carla
`
- report the result

The purpose of the experiment is compatibility, not accuracy.

### CODE REVIEW

**Comment by KonstantinosBarmpas** [comment]
@georgios-v  Followed your instructions. "navigate to 'CarND-Capstone/classifier/build'" there is no build file / folder in the classifier branch. Is the path correct ?

**Comment by georgios-v** [comment]
@KonstantinosBarmpas everything is correct. You have to be more careful, read instructions more thoroughly, and learn git and github. Github offers a complete set of tutorials and guides to both.

At the very top of this page is the name of the branch. It is **not** classifier!

I have created a **new** branch. Otherwise my prompt to remove the classifier branch would make no sense. How can you test deleted code?

**Comment by KonstantinosBarmpas** [comment]
After fixing the structure of your new branch I was able to run it using Udacity's workspace, I get the following error:
ValueError: No op named NonMaxSuppressionV3 in defined operations.

For feuture reference:

In order to compile and work all the files need to be in the same folder.
Please do not remove the .proto files again since they are important to organize the object_detection protocol. 

Conlusion:

After search the error seems to be as you suggested tensorflow compatibilty error. Meaning we canr use mobiletnet in tensorflow 1.3 although there are references that say we can.

Next steps:

I will re train the models using SSD Inception V2 Coco which is compatible with our tensorflow version and is fast. Give me the weekend to do it and test the compatibility with Udacity's workspace. @georgios-v

**Comment by KonstantinosBarmpas** [comment]
Issue fixed. Managed to find a previous version of the tensorflow model that supports v4. The models were extracted in v4. Run the .pb files in tensorflow v3 and they worked.

**Comment by KonstantinosBarmpas** [comment]
Issue fixed. Managed to find a previous version of the tensorflow model that supports v4. The models were extracted in v4. Run the .pb files in tensorflow v3 and they worked.

I have the files in the folders ending with _v4. 

@georgios-v  I think now you can do the timing measurements

**Comment by KonstantinosBarmpas** [comment]
@georgios-v  any news about the models ? please let me know as soon as possible if the timing is fine

**Pull request closed without merging**
